import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

// styles
import 'bootstrap/dist/css/bootstrap.min.css';
import "./../styles/globals.scss";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pr-br" className={`${dmSans.variable}`}>
      <body >
        {children}
      </body>
    </html>
  );
}
